-- Monitor configuration for Trotid Shell
-- Generated by nwg-displays on 2026-04-22

for _, m in ipairs({
    { output = "eDP-1",    mode = "1920x1080", refresh = 60, position = "0x0",    scale = 1.0, reserved_area = { top = -10, bottom = 0, left = 0, right = 0 } },
    { output = "HDMI-A-1", mode = "1920x1080", refresh = 50, position = "1920x0", scale = 1.0, reserved_area = { top = -10, bottom = 0, left = 0, right = 0 } },
}) do
    hl.monitor(m)
end

-- Workspace assignments
hl.workspace({ id = 1, monitor = "eDP-1", default = true })
hl.workspace({ id = 2, monitor = "eDP-1" })
hl.workspace({ id = 3, monitor = "eDP-1" })
hl.workspace({ id = 4, monitor = "HDMI-A-1", default = true })
hl.workspace({ id = 5, monitor = "HDMI-A-1" })
hl.workspace({ id = 6, monitor = "HDMI-A-1" })
hl.workspace({ id = 7, monitor = "HDMI-A-1" })
hl.workspace({ id = 8, monitor = "HDMI-A-1" })
hl.workspace({ id = 9, monitor = "HDMI-A-1" })
hl.workspace({ id = 10, monitor = "HDMI-A-1" })

