-- Monitor configuration for Trotid Shell
-- Auto-generated by installer based on detected hardware.
-- If no monitors are listed, Hyprland auto-detects all connected displays.
--
-- To customize, add entries like:
--   { output = "eDP-1", mode = "preferred", position = "0x0", scale = 1.0 },

for _, m in ipairs({
}) do
    hl.monitor(m)
end

